NavigationChallenge/Models/Address.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NavigationChallenge.Models
{
    public class Address
    {
        public string AddressTypeCode { get; set; }
        public int LocCodeQualifier { get; set; }
        public long LocationNumber { get; set; }
        public string AddressName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
    }
}

NavigationChallenge/Models/CarrierInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NavigationChallenge.Models
{
    public class CarrierInformation
    {
        public string TransMethodCode { get; set; }
        public string AlphaCode { get; set; }
        public string Routing { get; set; }
        public string DescriptionCode { get; set; }
    }
}

NavigationChallenge/Models/LineItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NavigationChallenge.Models
{
    public class LineItem
    {
        public int LineSequenceNumberId { get; set; }
        public string BuyerPartNumber { get; set; }
        public string VendorPartNumber { get; set; }
        public string ConsumerPackageCode { get; set; }
        public int OrderQty { get; set; }
        public string OrderQtyUOM { get; set; }
        public decimal PurchasePrice { get; set; }
    }
}

NavigationChallenge/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NavigationChallenge.Models
{
    public class Order
    {
        public string TradingPartnerId { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public DateTime PurchaseOrderDate { get; set; }

        public IList<Address> AddressList { get; set; }
        public CarrierInformation CarrierInfo { get; set; }
        public IList<LineItem> OrderItems { get; set; }

        public decimal TotalAmount { get; set; }
        public int TotalLineItemNumber { get; set; }
    }
}

NavigationChallenge/Models/OrderModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml;
using System.Xml.Linq;
using System.Xml.XPath;

namespace NavigationChallenge.Models
{
    public static class OrderModel
    {
        public static string GetNodeValue(XDocument doc, string nodePath, string elementName)
        {
            if (doc == null || string.IsNullOrEmpty(elementName) || string.IsNullOrEmpty(nodePath))
            {
                return "Parameters Missing";
            }
            try
            {
                string baseNode = "Orders/Order/";
                var element = doc.XPathSelectElement($"{baseNode}{nodePath}");
                return element.Element(elementName)?.Value;
                
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }

        public static T GetNodeValue<T>(XElement node, string nodeName)
        {
            var item = node.Element(nodeName)?.Value;
            return (T)Convert.ChangeType(item, typeof(T));

            //var item = node.Descendants(nodeName)?.Select(x => x.Value).ToString();
            //return (T)Convert.ChangeType(item, typeof(T));
        }
    }
}

NavigationChallenge/Controllers/NavigatorController.cs
using NavigationChallenge.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using System.Xml.XPath;

namespace NavigationChallenge.Controllers
{
    public class NavigatorController : Controller
    {
        // GET: Navigator
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ReadOrderForm()
        {
            string baseNode = "Orders/Order/";
            Order formOrder = new Order();
            formOrder.AddressList = new List<Address>();
            formOrder.OrderItems = new List<LineItem>();

            string navChallenge = Request.Files[0].FileName;
            string serverPath = Server.MapPath("~/Orders/");
            Request.Files[0].SaveAs(serverPath + navChallenge);
            string orderPath = Path.Combine(serverPath, navChallenge);

            XDocument xDoc = XDocument.Load(orderPath);
            
            string nodePath = "Header/OrderHeader";
            formOrder.TradingPartnerId = OrderModel.GetNodeValue(xDoc, nodePath, "TradingPartnerId");
            formOrder.PurchaseOrderNumber = OrderModel.GetNodeValue(xDoc, nodePath, "PurchaseOrderNumber");
            formOrder.PurchaseOrderDate = Convert.ToDateTime(OrderModel.GetNodeValue(xDoc, nodePath, "PurchaseOrderDate"));
            formOrder.TotalAmount = decimal.Parse(OrderModel.GetNodeValue(xDoc, "Summary", "TotalAmount"));
            formOrder.TotalLineItemNumber = int.Parse(OrderModel.GetNodeValue(xDoc, "Summary", "TotalLineItemNumber"));

            nodePath = "Header/CarrierInformation";
            CarrierInformation carryInfo = new CarrierInformation();
            carryInfo.TransMethodCode = OrderModel.GetNodeValue(xDoc, nodePath, "CarrierTransMethodCode");
            carryInfo.AlphaCode = OrderModel.GetNodeValue(xDoc, nodePath, "CarrierAlphaCode");
            carryInfo.Routing = OrderModel.GetNodeValue(xDoc, nodePath, "CarrierRouting");
            carryInfo.DescriptionCode = OrderModel.GetNodeValue(xDoc, nodePath, "EquipmentDescriptionCode");
            formOrder.CarrierInfo = carryInfo;

            //XmlNodeList nodeList = doc.SelectNodes("Orders/Order/Header/Address");
            nodePath = "Header/Address";
            var nodeList = xDoc.XPathSelectElements($"{baseNode}{nodePath}");
            foreach (XElement node in nodeList)
            {
                formOrder.AddressList.Add(new Address()
                {
                    AddressTypeCode = OrderModel.GetNodeValue<string>(node, "AddressTypeCode"),
                    LocCodeQualifier = OrderModel.GetNodeValue<int>(node, "LocationCodeQualifier"),
                    LocationNumber = OrderModel.GetNodeValue<long>(node, "AddressLocationNumber"),
                    AddressName = OrderModel.GetNodeValue<string>(node, "AddressName"),
                    Address1 = OrderModel.GetNodeValue<string>(node, "Address1"),
                    Address2 = OrderModel.GetNodeValue<string>(node, "Address2"),
                    City = OrderModel.GetNodeValue<string>(node, "City"),
                    State = OrderModel.GetNodeValue<string>(node, "State"),
                    PostalCode = OrderModel.GetNodeValue<string>(node, "PostalCode"),
                    CountryCode = OrderModel.GetNodeValue<string>(node, "Country")
                });
            }
            
            nodePath = "LineItem/OrderLine";
            var itemNodeList = xDoc.XPathSelectElements($"{baseNode}{nodePath}");
            foreach (XElement node in itemNodeList)
            {
                formOrder.OrderItems.Add(new LineItem()
                {
                    LineSequenceNumberId = OrderModel.GetNodeValue<int>(node, "LineSequenceNumber"),
                    BuyerPartNumber = OrderModel.GetNodeValue<string>(node, "BuyerPartNumber"),
                    VendorPartNumber = OrderModel.GetNodeValue<string>(node, "VendorPartNumber"),
                    ConsumerPackageCode = OrderModel.GetNodeValue<string>(node, "ConsumerPackageCode"),
                    OrderQty = OrderModel.GetNodeValue<int>(node, "OrderQty"),
                    OrderQtyUOM = OrderModel.GetNodeValue<string>(node, "OrderQtyUOM"),
                    PurchasePrice = OrderModel.GetNodeValue<decimal>(node, "PurchasePrice")
                });
            }

            return View(formOrder);
        }
    }
}

NavigationChallenge/Views/Navigator/Index.cshtml
@using (Html.BeginForm("ReadOrderForm", "Navigator", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group row">
        <div class="col-md-12 pt-2 pl-5">
            <div class="row">
                <label for="navOrder" class="col-form-label pr-3">Orders File</label>
                <input type="file" class="form-control-file" name="orderUpload" id="navOrder" />
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.ActionLink("Cancel", "", "Navigator", new { @class = "btn btn-sm btn-primary btn-width" })
        <button type="submit" class="btn btn-sm btn-primary btn-width">Submit</button>
    </div>
}

NavigationChallenge/Views/Navigator/ReadOrderForm.cshtml
@model NavigationChallenge.Models.Order

<div class="container-fluid col-md-6">
    <div class="row">
        <div class="col-md-6">Trading Partner</div>
        <div class="col-md-6">@Model.TradingPartnerId</div>
    </div>
    <div class="row">
        <div class="col-md-6">Order Number</div>
        <div class="col-md-6">@Model.PurchaseOrderNumber</div>
    </div>
    <div class="row">
        <div class="col-md-6">Order Date</div>
        <div class="col-md-6">@Model.PurchaseOrderDate</div>
    </div>
</div>
<br />
@foreach (var item in Model.AddressList)
{
<div class="container col-md-6 border">
    <div class="row">
        <div class="col-md-6">Address Name</div>
        <div class="col-md-6">@item.AddressName</div>
    </div>
    <div class="row">
        <div class="col-md-6">Address</div>
        <div class="col-md-6">@item.Address1</div>
    </div>
    <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-6">@item.Address2</div>
    </div>
    <div class="row">
        <div class="col-md-2">City</div>
        <div class="col-md-2">@item.City</div>
        <div class="col-md-2">State</div>
        <div class="col-md-2">@item.State</div>
    </div>
    <div class="row">
        <div class="col-md-2">Postal Code</div>
        <div class="col-md-2">@item.PostalCode</div>
        <div class="col-md-2">Country</div>
        <div class="col-md-2">@item.CountryCode</div>
    </div>
</div>
<br />
}

@foreach (var item in Model.OrderItems)
{
<div class="container col-md-6 border">
    <div class="row">
        <div class="col-md-6">Buyer Part Number</div>
        <div class="col-md-6">@item.BuyerPartNumber</div>
    </div>
    <div class="row">
        <div class="col-md-6">Vendor Part Number</div>
        <div class="col-md-6">@item.VendorPartNumber</div>
    </div>
    <div class="row">
        <div class="col-md-6">Quantity</div>
        <div class="col-md-6">@item.OrderQty</div>
    </div>
    <div class="row">
        <div class="col-md-6">Unit Of Messure</div>
        <div class="col-md-6">@item.OrderQtyUOM</div>
    </div>
    <div class="row">
        <div class="col-md-6">Price</div>
        <div class="col-md-6">@item.PurchasePrice</div>
    </div>
</div>
<br />
}

NavigationChallenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="navbar-header">
                @Html.ActionLink("Navigator Challenge", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/js")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>